server:
  port: 9090
spring:
  datasource:
    dialect: org.hibernate.dialect.PostgreSQLDialect
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Ornek
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show-sql: true