server:
  port: 3333
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          '[/**]':
            allowedOrigins: "*"
            allowedHeaders: "*"
            allowedMethods:
              - GET
              - POST
      routes:
        - id: main-service
          uri: http://10.76.6.72:9098
          predicates:
            - Path= /main/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/mainservice
        - id: auth-service
          uri: http://10.76.4.36:9090
          predicates:
            - Path= /auth/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/authservice
        - id: user-service
          uri: http://10.76.11.124:9091
          predicates:
            - Path= /user/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/userservice

        - id: corporation-service
          uri: http://10.76.7.40:8891
          predicates:
            - Path= /corporation/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/corporationservice
        - id: mail-service
          uri: http://10.76.5.161:9191
          predicates:
            - Path= /mail/**
          filters:
            - DedupeResponseHeader=Access-Control-Allow-Credentials Access-Control-Allow-Origin
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/mailservice

      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}
