server:
  port: 80

spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway-service
  cloud:
    gateway:
      routes:
        - id: main-service
          uri: http://10.8.3.169:9098
          predicates:
            - Path= /main/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/mainservice
        - id: auth-service
          uri: http://10.8.2.218:9090
          predicates:
            - Path= /auth/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/authservice
        - id: user-service
          uri: http://10.8.13.78:9091
          predicates:
            - Path= /user/**
          filters:
            - name: CircuitBreaker
              args:
                enabled: true
                fallbackUri: forward:/fallback/userservice
#        - id: mail-service
#          uri: http://localhost:8094
#          predicates:
#            - Path=/mail/**
#          filters:
#            - name: CircuitBreaker
#              args:
#                enabled: true
#                fallbackUri: forward:/fallback/mailservice
      default-filters:
        - RewritePath= /(?<segment>.*),/api/v1/$\{segment}
