spring:
  cloud:
    config:
      uri: http://10.8.0.17:8889
  profiles:
    active: properties
  config:
    import: "optional:configserver:"
  application:
    name: user-service-application

  data:
    mongodb:
      auto-index-creation: true
