apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongo-dep
  labels:
    team: mongodeployment
spec:
  selector:
    matchLabels:
      app: mongodb
  template:
    metadata:
      labels:
        app: mongodb
    spec:
      containers:
        - name: mongodb
          image: mongo
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.1"
            limits:
              memory: "512Mi"
              cpu: "0.2"
          ports:
            - containerPort: 27777
          env:
            - name : MONGO_INITDB_ROOT_USERNAME
              value: team3
            - name : MONGO_INITDB_ROOT_PASSWORD
              value: "root"
