apiVersion: v1
kind: Service
metadata:
  name: loadbalancer-postgre
  labels:
    app: postgreservice
spec:
  ports:
    - port: 5444
      targetPort: 5432
  selector:
    app: postgresql
  type: LoadBalancer