apiVersion: v1
kind: Service
metadata:
  name:  postgresql-loadbalancer
spec:
  selector:
    database: postgresql
  type:  LoadBalancer
  ports:
    - name:  tcppostgre
      port:  1111
      targetPort:  5432