apiVersion: apps/v1
kind: Deployment
metadata:
  name: api-gateway-deployment
  labels:
    team: team3
spec:
  selector:
    matchLabels:
      app: api-gateway
  template:
    metadata:
      labels:
        app: api-gateway
    spec:
      containers:
        - name: api-gateway-container
          image: burakozer1/team3api:v009
          resources:
            requests:
              memory: "512M"
              cpu: "0.05"
            limits:
              memory: "1Gi"
              cpu: "0.1"
          ports:
            - containerPort: 3333