apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service-deployment
  labels:
    team: team3
spec:
  selector:
    matchLabels:
      app: auth-service
  template:
    metadata:
      labels:
        app: auth-service
    spec:
      containers:
        - name: auth-service
          image: burakozer1/team3auth:v002
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.05"
            limits:
              memory: "2Gi"
              cpu: "0.1"
          ports:
            - containerPort: 9090
