apiVersion: apps/v1
kind: Deployment
metadata:
  name: config-service-deployment
  labels:
    team: team3
spec:
  selector:
    matchLabels:
      app: config-service
  template:
    metadata:
      labels:
        app: config-service
    spec:
      containers:
        - name: config-server-container
          image: burakozer1/team3config
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.1"
            limits:
              memory: "512Mi"
              cpu: "0.2"
          ports:
            - containerPort: 8889