apiVersion: apps/v1
kind: Deployment
metadata:
  name: main-service-deployment
  labels:
    team: team3
spec:
  selector:
    matchLabels:
      app: main-service
  template:
    metadata:
      labels:
        app: main-service
    spec:
      containers:
        - name: main-server-container
          image: mhkars/main2:v001
          resources:
            requests:
              memory: "128Mi"
              cpu: "0.1"
            limits:
              memory: "512Mi"
              cpu: "0.2"
          ports:
            - containerPort: 9098
