apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-hrm-deployment
  labels:
    team: team3
spec:
  selector:
    matchLabels:
      app: react-hrm
  template:
    metadata:
      labels:
        app: react-hrm
    spec:
      containers:
        - name: react-service
          image: mhkars/react:v003
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.2"
          ports:
            - containerPort: 3000

