apiVersion: apps/v1
kind: Deployment
metadata:
  name: react-deployment
  labels:
    app: reactwebdeployment
spec:
  selector:
    matchLabels:
      app: react-web-service
  template:
    metadata:
      labels:
        app: react-web-service
    spec:
      containers:
        - name: react-web-service
          image: burakozer1/react:v004
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.2"
          ports:
            - containerPort: 80
            - containerPort: 3000
