apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-service-deployment
  labels:
    team: team3
spec:
  selector:
    matchLabels:
      app: user-service
  template:
    metadata:
      labels:
        app: user-service
    spec:
      containers:
        - name: user-service
          image: burakozer1/team3user:v001
          resources:
            requests:
              memory: "1Gi"
              cpu: "0.1"
            limits:
              memory: "2Gi"
              cpu: "0.2"
          ports:
            - containerPort: 9091