apiVersion: v1
kind: Service
metadata:
  name: api-gateway-loadbalancer
spec:
  type: LoadBalancer
  selector:
    app: api-gateway

  ports:
    - port: 3333
      targetPort: 3333
      name: api-gateway-port
