apiVersion: v1
kind: Service
metadata:
  name: react-loadbalancer
  labels:
    app: reactapp
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: react-hrm
  type: LoadBalancer
