spring:
  cloud:
    config:
      uri: http://10.72.0.12:8889

  profiles:
    active: properties
  config:
    import: "configserver:"
  application:
    name: corporation-service-application
  data:
    mongodb:
      auto-index-creation: true

